service:
	gcc -Wall -o chall chall.c -lcap -pie
	strip ./chall
	mv ./chall ../service/bin/she_came_in_through_the_bathroom_window

clean:
	rm ../service/bin/* ../service/rw/*
	rm -rf ../service/append
