#!/usr/bin/env python2

from pwn import remote, process, context
import json
import sys
import traceback
# context.timeout = 45
context.log_level = 'error'

def get_flag(ip, port, flag_id, token):

    r = remote(ip, port)

    # Retrieve flag
    r.sendlineafter('> ', '3')
    r.sendlineafter('look at? ', str(token))

    song_end = '\n---------------------------------------------\nWhat would you like to do,'
    song = r.recvuntil(song_end)[:-len(song_end)]
    flag = song[song.index('__') + 2:]
    r.sendlineafter('> ', '4')
    r.close()

    response = {
        'error'   : 0,
        'error_msg' : '',
        'payload' : {
            'flag': flag,
        }
    }
    return response

if __name__ == "__main__":
    try:
        print json.dumps(get_flag(sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]))
    except Exception as e:
        response = {
            "error": 1,
            'error_msg' : str(e) + "\n" + traceback.format_exc(),
            "payload": {}
        }
        print json.dumps(response)
